version: '2'
services:
   es:
    #image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    image: ${CONTAINER_ELASTIC_IMAGE}:${ELASTIC_VERSION}
    restart: always
    container_name: ${PROJECT_NAME}_${CONTAINER_ELASTIC_NAME}
    volumes:
      - ./es:/usr/share/elasticsearch/data
    environment:
      - cluster.name=pim
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - devbox_network

networks:
   devbox_network:
     external: true
