version: '2'

services:
   redis:
    env_file: ./.env
    container_name: ${PROJECT_NAME}_${CONTAINER_REDIS_NAME}
    image: ${CONTAINER_REDIS_IMAGE}:${CONTAINER_REDIS_VERSION}
    restart: always
    networks:
      - devbox_network

networks:
   devbox_network:
     external: true
