version: '3'

services:
    mailhog:
        image: madebyewave/mailhog
        container_name: mailer
        restart: on-failure:5
        ports:
            - "${MAILHOG_PORT}:8025"
        networks:
            - docker_projectsubnetwork

networks:
    docker_projectsubnetwork:
        external: true
