version: "2"

options:
    project_root: config_path

syncs:
    {{PROJECT_NAME}}_{{CONTAINER_ELASTICSEARCH_NAME}}_data_sync:
        src: '{{DEVBOX_PROJECT_DIR}}/sysdumps/elasticsearch/data'
        sync_strategy: 'native'
