version: '3'

services:
    rabbitmq:
        image: {{CONTAINER_RABBITMQ_IMAGE}}:{{CONTAINER_RABBITMQ_VERSION}}
        container_name: {{PROJECT_NAME}}_{{CONTAINER_RABBITMQ_NAME}}
        restart: unless-stopped
        ports:
            - "1{{CONTAINER_RABBITMQ_PORT}}:15672"
            - "{{CONTAINER_RABBITMQ_PORT}}:5672"
        volumes:
            - ./configs/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        networks:
            - docker_projectsubnetwork

networks:
    docker_projectsubnetwork:
        external: true
