version: '3'

services:
    redis:
        image: {{CONTAINER_REDIS_IMAGE}}:{{CONTAINER_REDIS_VERSION}}
        container_name: {{PROJECT_NAME}}_{{CONTAINER_REDIS_NAME}}
        restart: on-failure:5
        networks:
            - docker_projectsubnetwork

networks:
    docker_projectsubnetwork:
        external: true
