version: "2"

options:
    project_root: config_path
#    verbose: true
    # comma-separated syncs list to show their logs
    devbox_show_logs_for_syncs: {{PROJECT_NAME}}_{{CONTAINER_WEB_NAME}}_public_html_sync

syncs:
    {{PROJECT_NAME}}_{{CONTAINER_WEB_NAME}}_public_html_sync:
        src: '{{DEVBOX_PROJECT_DIR}}/public_html'
        sync_strategy: 'native' # Linux specific, WinOs / MacOs specific have 'unison' strategy
        sync_userid: 33 # for unison/rsync strategies
        # See more unison options: https://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#prefs
        sync_args:
            # Prevent permissions updating
            - "-perms=0"
            - "-dontchmod=true"
            # Params
            - "-fastcheck=true"
            - "-fastercheckUNSAFE=true"
            - "-maxthreads=100"
            - "-ignorelocks=true"
            - "-numericids=false"
            - "-confirmbigdel=false"
        sync_excludes_type: 'none' # set 'none' explicitly otherwise default type 'Name' will be passed to exclude patterns
        sync_excludes:
            - 'Path .git'
            - 'Path .idea'
            - 'Path .gitignore'
            - 'Path .gitattributes'
    {{PROJECT_NAME}}_{{CONTAINER_WEB_NAME}}_composer_sync:
        src: '{{DEVBOX_PROJECT_DIR}}/share/composer'
        sync_strategy: 'native' # Linux specific, WinOs / MacOs specific have 'unison' strategy
        sync_userid: 33 # for unison/rsync strategies
